language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php:
        - nightly

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

# faster builds on new travis containers
sudo: false

install:
  - composer self-update && composer --version

before_script:
  - composer validate --no-check-all --strict
  - composer update $PREFER_LOWEST

script:
  - php testsuite.php --ci
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
